### PR TITLE
Cleaned solutions

### PR DESCRIPTION
**Pull request by kenmueller**
Hi, worked a bit on cleaning all the tests and solutions with formatting. Hope you like it!

### CODE REVIEW

**Comment by hiquest** [comment]
@kenmueller thank you, sir, this is very appreciated!

My only problem with it is that you use 8 spaces for tab formatting, while the industry standard currently is 2 space. Well, at least 4 (https://eslint.org/docs/rules/indent). So if you change this back to 2 spaces, I'll be happy to merge it!

Thank you.

**Comment by kenmueller** [comment]
If you want, I'll change it to 2 spaces, but I used a 4 tab, not an 8 space. For some reason GitHub shows 4 tabs as 8 spaces. You can try downloading it and see that they are not 8 spaces.

**Comment by hiquest** [comment]
Hey! Actually, I think you're using some weird tab character. At least this is what I see in my editor.

I'm merging it anyway, and I will fix it later.

**Comment by hiquest** [comment]
Thank you @kenmueller !

**Pull request merged**
